### ISSUE TITLE
Not entering "onAddTrack" function

### ISSUE THREAD

**Issue by saif-o99** [react-native-webrtc/react-native-webrtc#1241]
#### Observed Behavior

Connection is not able to reach to "onAddTrack".
this happens after i upgraded RN to 0.70.6 and the webrtc plugin to beta 7, same issue on beta 6. but this wasn't happening on my code before the upgrade.
also i'm not sure if its 100% plugin issue or in my code but i'm not able to know what can go wrong.

i did some logs here they are :

````@ReactMethod(isBlockingSynchronousMethod = true)
    public WritableMap peerConnectionAddTrack(int id,
                                              String trackId,
                                              ReadableMap options) {
        try {
            return (WritableMap) ThreadUtils.submitToExecutor((Callable<Object>) () -> {
                PeerConnectionObserver pco = mPeerConnectionObservers.get(id);
                Log.d(TAG, "peerConnectionAddTrack() " + "A");
                if (pco == null) {
                    Log.d(TAG, "peerConnectionAddTrack() peerConnection is null");
                    return null;
                }

                MediaStreamTrack track = getLocalTrack(trackId);
                if (track == null) {
                    Log.w(TAG, "peerConnectionAddTrack() couldn't find track " + trackId);
                    return null;
                }
                Log.d(TAG, "peerConnectionAddTrack() " + "B");
                List<String> streamIds = new ArrayList<>();
                if (options.hasKey("streamIds")) {
                    ReadableArray rawStreamIds = options.getArray("streamIds");
                    if (rawStreamIds != null) {
                        for (int i = 0; i < rawStreamIds.size(); i++) {
                        Log.d(TAG, "peerConnectionAddTrack() " + i + rawStreamIds.getString(i));
                            streamIds.add(rawStreamIds.getString(i));
                        }
                    }
                }
                Log.d(TAG, "peerConnectionAddTrack() " + pco.getPeerConnection());
                RtpSender sender = pco.getPeerConnection().addTrack(track, streamIds);
                Log.d(TAG, "peerConnectionAddTrack() " + "C");
                // Need to get the corresponding transceiver as well
                RtpTransceiver transceiver = pco.getTransceiver(sender.id());

                // We need the transceiver creation order to reorder the transceivers array
                // in the JS layer.
                WritableMap params = Arguments.createMap();
                params.putInt("transceiverOrder", pco.getNextTransceiverId());
                params.putMap("transceiver", SerializeUtils.serializeTransceiver(id, transceiver));
                params.putMap("sender", SerializeUtils.serializeSender(id, sender));
                Log.d(TAG, "peerConnectionAddTrack() " + "D");
                return params;
            }).get();
        } catch (InterruptedException | ExecutionException e) {
            Log.d(TAG, "peerConnectionAddTrack() " + e.getMessage());
            return null;
        }
    }
````

![image](https://user-images.githubusercontent.com/52207667/205129815-646dde34-1af5-4d77-9559-69e990fe9f4d.png)

#### Platform Information

* **React Native Version**: 0.70.6
* **Plugin Version**: beta-7
* **OS**: Android
* **OS Version**:  9/12/10

**Comment by saghul** [comment]
Not sure I understand what your problem is. The code does enter the function, as your prints illustrate. What problem are you running into?

**Comment by saif-o99** [comment]
**My issue is that the event listener "track" is not being called .**
the above logging is just to help you observe the issue.
so this function is being called but the function "OnAddTrack" inside the WebrtcModule.java is not being called.

**Comment by saghul** [comment]
Do you get here? https://github.com/react-native-webrtc/react-native-webrtc/blob/f78f3e6d10a234ba33e50c99c5df7f6c0480db0a/src/RTCPeerConnection.ts#L505

Note you'll get the event for each PC but we filter by PC id.

**Comment by saif-o99** [comment]
nope it doesn't reach here

**Comment by saghul** [comment]
Are you using any debugger tool?

**Comment by saif-o99** [comment]
i try logs for now because there is a package (realm) preventing me from going on debugging mode

**Comment by saif-o99** [comment]
there is also this crash on firebase, this cause the whole app to crash. might not be the same issue but maybe related.
![image](https://user-images.githubusercontent.com/52207667/205434863-3322c233-0c79-416b-a99e-26e2d0007677.png)
this started to showup after react native update also

**Comment by saghul** [comment]
> there is also this crash on firebase, this cause the whole app to crash. might not be the same issue but maybe related.
> 
> ![image](https://user-images.githubusercontent.com/52207667/205434863-3322c233-0c79-416b-a99e-26e2d0007677.png)
> 
> this started to showup after react native update also

Alas the backtrace contains no symbols...

Our binaries are un stripped so you should see something there I think.

**Comment by saghul** [comment]
> i try logs for now because there is a package (realm) preventing me from going on debugging mode

Hum. That's odd I haven't seen this.

I'll try to repro next week but last time I tried our app didn't see this.

Do you see any JS warning or error?

**Comment by saghul** [comment]
I think this might be the same problem as https://github.com/react-native-webrtc/react-native-webrtc/issues/1237, can you please test latest master?

**Comment by saghul** [comment]
Beta 8 is out, can you give it another try?

**Comment by saif-o99** [comment]
Sure will do, thanks for your efforts

**Comment by saghul** [comment]
Ping?

**Comment by saif-o99** [comment]
> Ping?

@saghul  sorry i was busy with another project. anyway, unfortunately the issue still there.

**Comment by saif-o99** [comment]
i'm gonna debug more

**Comment by saghul** [comment]
What version did you test? 106.0.0 stable has a new way to handle events which should happen so fast there is no way to miss any.

**Comment by saif-o99** [comment]
working on version 106.0.1.
then maybe its not related to the issue mentioned above.
i'm digging more

**Comment by saghul** [comment]
So does it or does it not fire? If you see the track event in JS then this issue is solved and your problem likely lies elsewhere.

**Comment by 8BallBomBom** [comment]
Sounds like he is using version 106.0.1 but still experiencing the issue.
Not having any luck reproducing, been spam adding/removing tracks so far.

@saif-o99 Can you provide a project that we can use to reproduce the issue?
Would help us to conclude if the issue lies within this module or not and then look at solutions 😃

**Comment by saif-o99** [comment]
Hey guys, i'm really sorry i kept you busy for this.
turned out its an issue with my code flow. the weird think that this wasn't happening before the update which made me open this ticket but i dont know what changed internally.
anyway thank you guys .

**Comment by 8BallBomBom** [comment]
No worries 👍🏻 
Sounds like you were experiencing the same issue as #1237 which was addressed in the latest update.
Pretty much resulted in some events not firing.
Glad things worked out 😄

**Comment by saif-o99** [comment]
@8BallBomBom but i still have a crash 🥲
i dont think its related to this issue. have a look at the image above
and this
`Fatal error in: gen/sdk/android/generated_metrics_jni/../../../../../../sdk/android/src/jni/jni_generator_helper.h,
 line 94 last system error: 0 # Check failed: !env->ExceptionCheck() 
`
do you know what could be the issue?

**Comment by 8BallBomBom** [comment]
Can't say i've experienced that sort of error before.
Could you open a new issue and provide more info?
Also are you sure it is caused by this module?

**Comment by saif-o99** [comment]
@8BallBomBom  is see the error got "rtc" tag thats why i think its related to the module

**Comment by saif-o99** [comment]
is there a necessity to enable proguard in debug mode ?

**Comment by saif-o99** [comment]
please check #1255
